### ISSUE TITLE
As a team, we want a database schema. 

### ISSUE THREAD

**Issue by NGamblin** [64931ccc37d0555f7b3e29f39992d6c0/Project_2#2]
Database: adoptions_org

Users Table
-user_id : auto int 
-username: varchar(255)
-password: varchar(255)
-email: varchar(255)
-Favorites: varchar(255)

Dogs Table

-dog_id
-dog_name
-dog_breed
-dog_age
-dog_img_url
-dog_blurb

**Comment by anncoleman3** [comment]
C:\Users\annco\Project_2\database\schema.sql
